version: "3"

services:
  mariadb:
    image: "mariadb:10.7.1"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "springbootdb"
    networks:
      - internal

  backend:
    depends_on:
      - mariadb
      - smtpserver
    image: "${BACKEND_TAG}"
    restart: 'always'
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/springbootdb
      - SPRING_DATASOURCE_USERNAME=root
      - "SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - "SERVER_PORT=${BACKEND_PORT}"
    networks:
      - internal


networks:
  internal:
    external: false